package com.cognizant.training.feedbacktrack.service;

import com.cognizant.training.feedbacktrack.dto.EngagementTrendDTO;
import com.cognizant.training.feedbacktrack.dto.UserResponseDTO;
import com.cognizant.training.feedbacktrack.enums.FeedbackAction;
import com.cognizant.training.feedbacktrack.enums.Role;
import com.cognizant.training.feedbacktrack.exceptions.UnauthorizedAccessException;
import com.cognizant.training.feedbacktrack.feign.FeedbackClient;
import com.cognizant.training.feedbacktrack.feign.RecognitionClient;
import com.cognizant.training.feedbacktrack.feign.UserClient;
import com.cognizant.training.feedbacktrack.repository.ReviewRepository;
import feign.FeignException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class EngagementService {


    private final ReviewRepository reviewRepository;


     private final UserClient userClient;


    public EngagementTrendDTO getTrendForReviewer(Long reviewerId, Integer months) {
        log.info("Generating reviewer trend: reviewerId={}, requestedMonths={}", reviewerId, months);
        UserResponseDTO requester = fetchUserOrFail(getCurrentUserId());
        if(!reviewerId.equals(requester.getUserId()) && !requester.getRole().equals(Role.ADMIN)){
            throw new UnauthorizedAccessException("Access Denied: You can only view your own reviewer trend.");
        }
        validateId(reviewerId, "reviewerId");
        int window = resolveWindow(months);
        LocalDateTime from=LocalDateTime.now().minusMonths(window).withDayOfMonth(1).toLocalDate().atStartOfDay();
        LocalDateTime to  =LocalDateTime.now();
        List<Object[]> actionRows=reviewRepository.countByActionForReviewer(reviewerId);
        Map<FeedbackAction, Long> breakdown=toActionBreakdown(actionRows);
        List<Object[]> monthlyRows=reviewRepository.countMonthlyByReviewer(reviewerId, from, to);
        List<EngagementTrendDTO.MonthlyActivity> monthlyTrend=toMonthlyActivity(monthlyRows);
        log.debug("Reviewer trend intermediate data: reviewerId={}, actionRows={}, monthlyRows={}", reviewerId, actionRows.size(), monthlyRows.size());
        long total=breakdown.values().stream().mapToLong(Long::longValue).sum();
        Double resolutionRate=computeResolutionRate(breakdown, total);
        log.info("Trend generated for reviewerId={}, window={}m, total={}, monthlyPoints={}", reviewerId, window, total, monthlyTrend.size());
        return EngagementTrendDTO.builder()
                .actionBreakdown(breakdown)
                .resolutionRatePercent(resolutionRate)
                .monthlyTrend(monthlyTrend)
                .totalReviews(total)
                .build();

    }

    public EngagementTrendDTO getGlobalTrend(Long currentUserId, Integer months) {
        log.info("Generating global trend: currentUserId={}, requestedMonths={}", currentUserId, months);
        validateId(currentUserId, "currentUserId");
        int window = resolveWindow(months);
        UserResponseDTO requester = fetchUserOrFail(currentUserId);
        ensureAdmin(requester, "Access Denied: Admin role required.");

        LocalDateTime from = LocalDateTime.now().minusMonths(window).withDayOfMonth(1).toLocalDate().atStartOfDay();
        LocalDateTime to   = LocalDateTime.now();

        List<Object[]> actionRows  = reviewRepository.countByActionGlobal();
        Map<FeedbackAction, Long> breakdown = toActionBreakdown(actionRows);

        List<Object[]> monthlyRows = reviewRepository.countMonthlyGlobal(from, to);
        List<EngagementTrendDTO.MonthlyActivity> monthlyTrend = toMonthlyActivity(monthlyRows);
        log.debug("Global trend intermediate data: actionRows={}, monthlyRows={}", actionRows.size(), monthlyRows.size());

        long total = breakdown.values().stream().mapToLong(Long::longValue).sum();
        Double resolutionRate = computeResolutionRate(breakdown, total);

        log.info("Global trend generated by userId={}, window={}m, total={}", currentUserId, window, total);
        return EngagementTrendDTO.builder()
                .actionBreakdown(breakdown)
                .resolutionRatePercent(resolutionRate)
                .monthlyTrend(monthlyTrend)
                .totalReviews(total)
                .build();
    }

    private Map<FeedbackAction, Long> toActionBreakdown(List<Object[]> rows){
        log.debug("Transforming action breakdown rows: count={}", rows.size());
        Map<FeedbackAction, Long> res=new EnumMap<>(FeedbackAction.class);
        for(FeedbackAction action:FeedbackAction.values()){
            res.put(action, 0L);
        }
        for(Object[] row:rows) {
            res.put((FeedbackAction) row[0], ((Number) row[1]).longValue());
        }
        log.debug("Action breakdown map generated: keys={}, totalActions={}", res.keySet(), res.values().stream().mapToLong(Long::longValue).sum());
        return res;
    }

    private List<EngagementTrendDTO.MonthlyActivity> toMonthlyActivity(List<Object[]> rows) {
        log.debug("Transforming monthly activity rows: count={}", rows.size());
        List<EngagementTrendDTO.MonthlyActivity> monthlyActivity = rows.stream()
                .map(row -> EngagementTrendDTO.MonthlyActivity.builder()
                        .year(((Number) row[0]).intValue())
                        .month(((Number) row[1]).intValue())
                        .reviewCount(((Number) row[2]).longValue())
                        .build())
                .collect(Collectors.toList());
        log.debug("Monthly activity generated: points={}", monthlyActivity.size());
        return monthlyActivity;
    }

    private Double computeResolutionRate(Map<FeedbackAction, Long> breakdown, long total) {
        if (total == 0) {
            log.debug("Resolution rate skipped because total reviews is zero.");
            return null; // Avoid division by zero; no reviews means no resolution rate
        }
        long resolvedCount = breakdown.getOrDefault(FeedbackAction.RESOLVED, 0L);
        Double resolutionRate = (resolvedCount * 100.0) / total;
        log.debug("Resolution rate calculated: resolvedCount={}, total={}, rate={}", resolvedCount, total, resolutionRate);
        return resolutionRate;
    }

    private void validateId(Long id, String name){
        if(id==null || id<=0){
            log.warn("Invalid id provided: {}={}", name, id);
            throw new IllegalArgumentException(name + " must be a positive non-null value.");
        }
    }

    private int resolveWindow(Integer months){
        if (months == null || months <= 0) {
            log.warn("Invalid or missing months '{}', defaulting to 6.", months);
            return 6; // default to 6 months
        }
        if (months > 24) {
            log.warn("Requested months '{}' exceeds max window. Capping to 24.", months);
            return 24;
        }
        return months;
    }

    private UserResponseDTO fetchUserOrFail(Long userId) {
        try {
            UserResponseDTO user = userClient.getUserById(userId);
            return user;
        } catch (FeignException.NotFound ex) {
            throw new IllegalStateException("User with id " + userId + " does not exist.");
        } catch (FeignException ex) {
            throw new IllegalStateException("Unable to validate user due to downstream service error.");
        }
    }


    private void ensureAdmin(UserResponseDTO user, String message) {
        if (!hasRole(user, Role.ADMIN)) {
            throw new UnauthorizedAccessException(message);
        }
    }

    private boolean hasRole(UserResponseDTO user, Role role) {
        return user != null && user.getRole() == role;
    }

    private Long getCurrentUserId() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        return Long.parseLong(authentication.getPrincipal().toString());
    }
}
